PATH=/lhome/akhila/Desktop/ICNforIoT/code_data_ccnlite_svn/efficientiot/code_data/ccn-lite/bin:$PATH
#PATH=/lhome/akhila/Desktop/ICNforIoT/code_data_ccnlite_svn/efficientiot/code_data/ccn-lite-original/bin:$PATH
# configuration parameters

#Start relays and log output into files
numOfNodes=34
nodeNum=1
while [ $nodeNum -le $numOfNodes ]
do
   portNum=`expr $nodeNum + 9000`
   ccn-lite-relay -v trace -s ccnx2015 -u $portNum -x "/tmp/mgmt-relay-$nodeNum.sock" 2>&1 | grep "ICNIoT" > "log_node$nodeNum.txt" &
   nodeNum=`expr $nodeNum + 1`
done

sleep 15

#connect relays and add forwarding rules
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock newUDPface any 127.0.0.1 9031 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock newUDPface any 127.0.0.1 9031 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock newUDPface any 127.0.0.1 9032 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock newUDPface any 127.0.0.1 9032 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-16.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock newUDPface any 127.0.0.1 9033 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock newUDPface any 127.0.0.1 9033 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock newUDPface any 127.0.0.1 9034 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-19.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock newUDPface any 127.0.0.1 9034 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock newUDPface any 127.0.0.1 9001 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock newUDPface any 127.0.0.1 9002 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock newUDPface any 127.0.0.1 9003 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock newUDPface any 127.0.0.1 9004 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock newUDPface any 127.0.0.1 9005 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock newUDPface any 127.0.0.1 9006 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-23.sock newUDPface any 127.0.0.1 9007 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-23.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-23.sock newUDPface any 127.0.0.1 9008 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-23.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-23.sock newUDPface any 127.0.0.1 9009 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-23.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-24.sock newUDPface any 127.0.0.1 9010 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-24.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-24.sock newUDPface any 127.0.0.1 9011 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-24.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-24.sock newUDPface any 127.0.0.1 9012 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-24.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-25.sock newUDPface any 127.0.0.1 9021 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-25.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-25.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-25.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-25.sock newUDPface any 127.0.0.1 9022 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-25.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-25.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-25.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-26.sock newUDPface any 127.0.0.1 9023 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-26.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-26.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-26.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-26.sock newUDPface any 127.0.0.1 9024 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-26.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-26.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-26.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock newUDPface any 127.0.0.1 9025 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock newUDPface any 127.0.0.1 9028 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock newUDPface any 127.0.0.1 9026 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock newUDPface any 127.0.0.1 9027 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock newUDPface any 127.0.0.1 9027 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock newUDPface any 127.0.0.1 9028 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-30.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock newUDPface any 127.0.0.1 9029 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-31.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock newUDPface any 127.0.0.1 9029 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-32.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock newUDPface any 127.0.0.1 9030 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-33.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock newUDPface any 127.0.0.1 9030 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s12 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s10 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s11 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s8 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s9 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s2 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s3 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s4 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s5 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-34.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml

