PATH=/lhome/akhila/Desktop/ICNforIoT/code_data_ccnlite_svn/efficientiot/code_data/ccn-lite/bin:$PATH
#Start relays and log output into files
numOfNodes=30
nodeNum=1
while [ $nodeNum -le $numOfNodes ]
do
   portNum=`expr $nodeNum + 9000`
   ccn-lite-relay -v trace -s ccnx2015 -u $portNum -x "/tmp/mgmt-relay-$nodeNum.sock" 2>&1 | grep "ICNIoT" > "log_node$nodeNum.txt" &
   nodeNum=`expr $nodeNum + 1`
done

sleep 3

#connect relays and add forwarding rules
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock newUDPface any 127.0.0.1 9001 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock newUDPface any 127.0.0.1 9003 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock newUDPface any 127.0.0.1 9004 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock newUDPface any 127.0.0.1 9019 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-2.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock newUDPface any 127.0.0.1 9002 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock newUDPface any 127.0.0.1 9006 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock newUDPface any 127.0.0.1 9007 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock newUDPface any 127.0.0.1 9013 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-3.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock newUDPface any 127.0.0.1 9002 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock newUDPface any 127.0.0.1 9012 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock newUDPface any 127.0.0.1 9030 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-4.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock newUDPface any 127.0.0.1 9003 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-5.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-7.sock newUDPface any 127.0.0.1 9025 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-7.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock newUDPface any 127.0.0.1 9002 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-8.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock newUDPface any 127.0.0.1 9008 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-9.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock newUDPface any 127.0.0.1 9002 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-10.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock newUDPface any 127.0.0.1 9004 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-11.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock newUDPface any 127.0.0.1 9004 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock newUDPface any 127.0.0.1 9026 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-12.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock newUDPface any 127.0.0.1 9003 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock newUDPface any 127.0.0.1 9016 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock newUDPface any 127.0.0.1 9023 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock newUDPface any 127.0.0.1 9024 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-13.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock newUDPface any 127.0.0.1 9002 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-14.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock newUDPface any 127.0.0.1 9003 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-15.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock newUDPface any 127.0.0.1 9003 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-17.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock newUDPface any 127.0.0.1 9003 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-18.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock newUDPface any 127.0.0.1 9002 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-20.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock newUDPface any 127.0.0.1 9011 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-21.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock newUDPface any 127.0.0.1 9002 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-22.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock newUDPface any 127.0.0.1 9004 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-27.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock newUDPface any 127.0.0.1 9004 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-28.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml
FACEID=`ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock newUDPface any 127.0.0.1 9010 | ccn-lite-ccnb2xml | grep FACEID | sed -e 's/^[^0-9]*\([0-9]\+\).*/\1/'`
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s16 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s23 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s19 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s30 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s26 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s25 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s24 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s1 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s6 $FACEID ccnx2015 | ccn-lite-ccnb2xml
ccn-lite-ctrl -x /tmp/mgmt-relay-29.sock prefixreg /n=s7 $FACEID ccnx2015 | ccn-lite-ccnb2xml

